### PR TITLE
Match hidden files that begin with two dots

### PR DESCRIPTION
**Pull request by chambln**
Admittedly not the most elegant solution but it works as far as I can tell using the files shown below as a test.

```
shfm » tree
.
├── empty/
├── .github/
│   └── workflows/
│       └── main.yml
├── .onlyhidden/
│   ├── ..hidden
│   └── .hidden
├── onlyhidden/
│   ├── ..hidden
│   └── .hidden
├── star/
│   ├── *
│   └── ..?*
├── star2/
│   ├── **
│   └── .[!.]*
├── ..foo
├── LICENSE
├── README
└── shfm*
```

It's very difficult to reason about how any of this works!

### CODE REVIEW

**Comment by chambln** [comment]
It's as if the `list_print` function doesn't know whether or not we've matched for hidden files and has to reverse engineer the expanded or unexpanded globs to figure out which ones really exist, all so it can print a slightly different message (`empty` vs. `no hidden files`).

**Comment by chambln** [comment]
At first I tried dropping args for files that don't exist:

```sh
for file do
    shift
    [ -e "$file" ] && set -- "$@" "$file"
done
```

or even `for file in "$1" "$2"; do ...` since only the first two args are potentially non-existent unexpanded globs.  However this approach led to all sorts of arcane problems—maybe @dylanaraps can offer some insight?

**Comment by chambln** [comment]
I just put [this](https://github.com/chambln/shfm/commit/34ee32b82462bd144f2500296517af886557b856) together.  This seems to work just as well and is *arguably*, *slightly* more elegant (or less horrendous, if you like).

```diff
commit 34ee32b82462bd144f2500296517af886557b856
Author: Gregory Chamberlain <greg@cosine.blue>
Date:   Thu Sep 24 03:17:54 2020 +0100

    Match hidden files that begin with two dots

diff --git a/shfm b/shfm
index 972025a..8e3accb 100755
--- a/shfm
+++ b/shfm
@@ -331,8 +331,19 @@ main() {
 
             .?)
                 case ${hidden:=1} in
-                    1) hidden=0; set -- .[!.]* ;;
-                    *) hidden=1; set -- *      ;;
+                    1)
+                        hidden=0
+                        set -- ..?* .[!.]*
+                        for file do
+                            shift
+                            [ -e "$file" ] && set -- "$@" "$file"
+                        done
+                        set -- "${@:-.[!.]*}"
+                        ;;
+                    *)
+                        hidden=1
+                        set -- *
+                        ;;
                 esac
 
                 y=1 y2=1 cur=$1
```

This drops non-existent unexpanded globs *before* handing it off to `list_print`.  If no matches survive said dropping process, then we have to awkardly shove `.[!.]*` back in there (see `"${@:-.[!.]*}"` above) because `list_print` expects to see it.

I can make a PR for this instead if needed (it's on a [different branch](https://github.com/chambln/shfm/tree/doubledot2)).

**Comment by dylanaraps** [comment]
Fixed: https://github.com/dylanaraps/shfm/commit/892017875386d31970bd7329c19646469ccf2676

**Pull request closed without merging**
